"""Write the Chapter 3 bundle: one Markdown file for the thesis draft.

    uv run python -m ch3.tools.bundle [--out PATH]

Same format as the Chapter 2 bundle (``export/CH2_bundle.md``): each file is
copied verbatim, preceded by ``\\n\\n<!-- ===== FILE: <path> ===== -->\\n\\n``.
The header carries the repo-relative path. At the end comes a manifest of the
raw evidence, generated from ``rawindex`` (the same counting as
``npm run exp:check``). No raw JSONL is included.

The default output is ``export/CH3_bundle.md`` in the main checkout, next to
``CH2_bundle.md``. ``export/`` is git-ignored: the bundle is never committed.
Rebuild it after any change to the bundled files.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path

from ch3.lib.conditions import conditions
from ch3.lib.env import RAW, ROOT
from ch3.tools.rawindex import by_condition, excluded, load_runs

FILES = [
    "ch3/results/RESULTS.md",
    "ch3/results/OBSERVATIONS.md",
    "ch3/results/SPEC_VS_IMPL.md",
    "ch3/results/INTERPRETATION_NOTES.md",
    "ch3/results/ENVIRONMENT.md",
    "ch3/README.md",
    "ch3/HYPOTHESES.md",
    "ch3/docs/spec_quotes.md",
]
MANIFEST_HEADER = "<!-- ===== MANIFEST: raw runs (generated by ch3/tools/bundle.py, not a file) ===== -->"
REP = re.compile(r"-r(\d+)\.jsonl$")


def header(path: str) -> str:
    return f"\n\n<!-- ===== FILE: {path} ===== -->\n\n"


def main_checkout() -> Path:
    common = subprocess.run(["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
                            cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
    return Path(common).parent


def rep_ranges(reps: list[int]) -> str:
    reps, out, start = sorted(reps), [], None
    for i, rep in enumerate(reps):
        start = rep if start is None else start
        if i + 1 == len(reps) or reps[i + 1] != rep + 1:
            out.append(f"r{start:02d}" if start == rep else f"r{start:02d}–r{rep:02d}")
            start = None
    return ", ".join(out) or "—"


def excluded_by_condition() -> dict[tuple[int, tuple[str, str, str]], list[str]]:
    out: dict = {}
    for rel in excluded():
        with (RAW / rel).open(encoding="utf-8") as handle:
            start = json.loads(handle.readline())
        key = (int(start["full_run"]), (start["phase"], start["config"], start["variant"]))
        out.setdefault(key, []).append(rel)
    return out


def manifest() -> str:
    runs = load_runs()
    grouped = by_condition(runs)
    skipped = excluded_by_condition()
    full_runs = sorted({r.full_run for r in runs})
    lines = [
        "# Manifest of the raw evidence (Chapter 3)",
        "",
        "Generated by `uv run python -m ch3.tools.bundle` from `ch3/results/raw/`, with the same "
        "counting as `npm run exp:check` (`ch3/tools/rawindex.py`). The raw JSONL is not included "
        "in this bundle. \"Counted\" = completed runs not listed in `raw/EXCLUDED.tsv`; the rep "
        "numbers come from the file names. Excluded files stay on disk; their reasons are in "
        "`raw/EXCLUDED.tsv` and `OBSERVATIONS.md`.",
        "",
        "| Condition | Full run | Counted runs | Failed | Reps | Excluded raw files | Raw path |",
        "|---|---|---|---|---|---|---|",
    ]
    total = failed_total = 0
    for cond in conditions():
        for fr in full_runs:
            group = grouped.get((fr, cond), [])
            done = [r for r in group if r.completed]
            failed = len(group) - len(done)
            total, failed_total = total + len(done), failed_total + failed
            reps = [int(m.group(1)) for r in done if (m := REP.search(r.path.name))]
            gone = ", ".join(f"`{Path(rel).name}`" for rel in sorted(skipped.get((fr, cond), []))) or "—"
            lines.append(f"| {'/'.join(cond)} | {fr} | {len(done)} | {failed} | {rep_ranges(reps)} | {gone} | "
                         f"`ch3/results/raw/{cond[0]}/{cond[1]}/` |")
    lines += [
        "",
        f"Totals: {len(conditions())} conditions × {len(full_runs)} full runs; {total} counted runs, "
        f"{failed_total} failed; {len(excluded())} raw files excluded. Integrity: every counted raw file's "
        "sha256 is recorded in `ch3/results/raw/MANIFEST.sha256` and re-checked by `npm run exp:check`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()
    out = args.out or main_checkout() / "export" / "CH3_bundle.md"
    dirty = subprocess.run(["git", "status", "--porcelain", "--", *FILES], cwd=ROOT,
                           capture_output=True, text=True, check=True).stdout.strip()
    if dirty:
        print(f"warning: bundling uncommitted changes:\n{dirty}")
    parts = [header(path) + (ROOT / path).read_text(encoding="utf-8") for path in FILES]
    parts.append(f"\n\n{MANIFEST_HEADER}\n\n" + manifest())
    text = "".join(parts)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}: {len(text)} characters, {len(FILES)} files + manifest")
    for path in FILES:
        print(f"  - {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
