"""Mint client credentials for the seeded Chapter 3 accounts.

CSS ``--seedConfig`` creates the accounts, pods and WebIDs (alice, appr, bob)
but cannot create client credentials. This logs in to each seeded account
through the CSS account API (reusing ``solidlib/provision.py``) and writes the
credentials to ``ch3/.state/.env``. Secrets are shown by CSS once; they are
written straight to the file and never printed.
"""

from __future__ import annotations

import json
import os

from ch3.lib.env import CH3, CONFIGS, ENV_PATH, base_url
from solidlib.provision import create_client_credentials, get_controls, login


def main() -> int:
    seed = json.loads((CH3 / "config" / "seed.json").read_text())
    lines = ["# Generated by ch3/start.sh -- DO NOT COMMIT (git-ignored).", ""]
    for config in CONFIGS:
        base = base_url(config)
        for account in seed:
            pod_name = account["pods"][0]["name"]
            print(f"  credentials for {pod_name} on {config} ({base})", flush=True)
            token, _ = login(base, account["email"], account["password"])
            controls = get_controls(base, token)
            pod_url = f"{base}{pod_name}/"
            web_id = f"{pod_url}profile/card#me"
            creds = create_client_credentials(controls, token, "ch3", web_id)
            prefix = f"{config.upper()}_{pod_name.upper()}_"
            lines += [
                f"{prefix}POD={pod_url}",
                f"{prefix}WEBID={web_id}",
                f"{prefix}CLIENT_ID={creds['id']}",
                f"{prefix}CLIENT_SECRET={creds['secret']}",
                "",
            ]
    ENV_PATH.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(ENV_PATH, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as handle:
        handle.write("\n".join(lines))
    print(f"  wrote {ENV_PATH.relative_to(CH3.parent)} (secrets not printed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
