"""Provision the lab's users and write their credentials to .env.

Creates, via the browser-free CSS account API:

* ``alice``  on server A (:3000) -- the data subject
* ``bob``    on server A (:3000) -- the recipient of shared data
* ``alice2`` on server B (:3001) -- Alice's account at a second provider,
  the destination for the portability experiment

Client secrets are displayed by CSS exactly once and cannot be read back, so
they are written straight to ``.env`` and never printed to the terminal.
``.env`` is git-ignored.

Run indirectly via ``./start.sh``; this module is not meant to be imported.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from solidlib.provision import provision_user  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"

ISSUER_A = os.environ.get("ISSUER_A", "http://localhost:3000")
ISSUER_B = os.environ.get("ISSUER_B", "http://localhost:3001")
WEBID_HOST = os.environ.get("WEBID_HOST", "http://localhost:3002")

# Fictional credentials for a local-only lab. These are not secrets in any
# meaningful sense, but they are still kept out of git along with the tokens.
USERS = [
    ("ALICE", ISSUER_A, "alice@example.org", "alice-lab-password", "alice"),
    ("BOB", ISSUER_A, "bob@example.org", "bob-lab-password", "bob"),
    ("ALICE2", ISSUER_B, "alice2@example.org", "alice2-lab-password", "alice2"),
]


def main() -> int:
    lines = [
        "# Generated by ./start.sh -- DO NOT COMMIT (see .gitignore).",
        "# Client secrets are shown by CSS exactly once; regenerate with",
        "# ./start.sh --reset if this file is lost.",
        "",
        f"ISSUER={ISSUER_A}",
        f"ISSUER_A={ISSUER_A}",
        f"ISSUER_B={ISSUER_B}",
        f"WEBID_HOST={WEBID_HOST}",
        "",
    ]

    for prefix, issuer, email, password, pod in USERS:
        print(f"  provisioning {pod} on {issuer} ...", flush=True)
        identity = provision_user(issuer, email, password, pod)
        lines += [
            f"{prefix}_ISSUER={issuer}",
            f"{prefix}_EMAIL={identity.email}",
            f"{prefix}_PASSWORD={password}",
            f"{prefix}_POD={identity.pod_url}",
            f"{prefix}_WEBID={identity.web_id}",
            f"{prefix}_CLIENT_ID={identity.client_id}",
            f"{prefix}_CLIENT_SECRET={identity.client_secret}",
            "",
        ]
        # Never print the secret itself.
        print(f"    -> pod {identity.pod_url}  (credentials written to .env)")

    ENV_PATH.write_text("\n".join(lines))
    ENV_PATH.chmod(0o600)
    print(f"\n  .env written ({len(USERS)} identities). Secrets were not printed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
